.uno/CodeCompletion/ux15/ColorPalette.g.uno
.uno/CodeCompletion/ux15/MainView.g.uno
.uno/CodeCompletion/ux15/StaticResources.g.uno
.uno/CodeCompletion/ux15/BaseText.g.uno
.uno/CodeCompletion/ux15/BoldText.g.uno
.uno/CodeCompletion/ux15/BottomBarIcon.g.uno
.uno/CodeCompletion/ux15/HomeIcon.g.uno
.uno/CodeCompletion/ux15/LogsIcon.g.uno
.uno/CodeCompletion/ux15/GoalsIcon.g.uno
.uno/CodeCompletion/ux15/ProfileIcon.g.uno
.uno/CodeCompletion/ux15/login.g.uno
.uno/CodeCompletion/ux15/Tab.g.uno
.uno/CodeCompletion/ux15/WelcomeText.g.uno
.uno/CodeCompletion/ux15/mainviewBis.g.uno
.uno/CodeCompletion/ux15/signupBis.g.uno
.uno/CodeCompletion/ux15/contract.g.uno
.uno/CodeCompletion/ux15/home.g.uno
.uno/CodeCompletion/ux15/mainviewInd.g.uno
.uno/CodeCompletion/ux15/TabHeader.g.uno
.uno/CodeCompletion/ux15/TabIcon.g.uno
.uno/CodeCompletion/ux15/PagePlaceholder.g.uno
.uno/CodeCompletion/ux15/signupInd.g.uno
.uno/CodeCompletion/ux15/albachain.unoproj.g.uno